name: Build project

on: [push, pull_request, workflow_dispatch]

jobs:
  buildWindows64:
    name: Build for ${{ matrix.targetPlatform }}
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    #runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          #customImage: 'unityci/editor:ubuntu-2021.3.0f1-windows-mono-1.0.1'
          customImage: 'unityci/editor:2021.3.0f1-windows-mono-1'
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}